=== invisiblek/kernel_808l/drivers/net/eip93_drivers/quickSec/src/ipsec/quicksec/apps/quicksec.dtd
<!-- 									-->
<!-- quicksec.dtd							-->
<!--  									-->
<!-- Copyright (c) 2002-2009 SFNT Finland Oy.                    	-->
<!--               All rights reserved.					-->
<!--  									-->
<!-- Document type description for QuickSec XML policy files.		-->
<!--									-->
<!--									-->

<!-- Built-in entities: 						-->
<!--									-->
<!--   quicksec:hostname  						-->
<!--   quicksec:version   						-->
<!--   quicksec:ifname(IFINDEX[,TYPE]) 					-->
<!--     where:  							-->
<!--       IFINDEX	is the interface number 			-->
<!--       TYPE		is `any', `loopback' or `physical'	  	-->
<!--									-->


<!-- Tunable parameters used in the policy. -->

<!ENTITY vpn-a-transform 	'esp 3des sha1'>

<!ENTITY vpn-a-group 	'2'>

<!ENTITY vpn-a-ike-life 	'86400'>

<!ENTITY vpn-a-ipsec-life 	'28800'>

<!ENTITY vpn-b-transform 	'esp aes xcbc-aes'>

<!ENTITY vpn-b-group 	'14'>

<!ENTITY vpn-b-ike-life 	'86400'>

<!ENTITY vpn-b-ipsec-life 	'28800'>

<!-- Default lifetime type. -->
<!ENTITY % default-life-type	'"kbytes"'>

<!-- Default rule type. -->
<!ENTITY % default-rule-type	'"pass"'>

<!-- Policy elements and their attributes. -->

<!-- The top-level element. -->
<!ELEMENT quicksec	(params?,policy+)>

<!-- Parameter element. -->
<!ELEMENT params (internal-nat?,engine-params?,engine-flows?
                  ,audit?,http-interface?
                  ,dns?
                  ,xauth-tester?
		  ,mobike?
                  ,(address-pool|externalkey|ldap|client-auth|
                    nat|group|route|media|tcpencap|auth-domain)*
                  ,xauth-method?)>

<!-- cookie-required : with ikev2 always do cookie exchange -->
<!-- certificate-provider : enable hash-and-url certificate provider -->
<!-- certificate-bundles : send hash-and-url certificates as bundles -->
<!ATTLIST params
          flags                         NMTOKENS   	#IMPLIED
          debug				CDATA           #IMPLIED
          kernel-debug			CDATA           #IMPLIED
          certificate-provider-port     CDATA		"7369">

<!-- Engine Parameters. -->
<!ELEMENT engine-params 		EMPTY>
<!ATTLIST engine-params
          decrement-ttl 		CDATA	#IMPLIED
          audit-corrupt                 CDATA   #IMPLIED
          drop-if-cannot-audit          CDATA   #IMPLIED
          min-ttl                      	CDATA	#IMPLIED
          audit-total-rate-limit       	CDATA	#IMPLIED
          flow-rate-always-allow       	CDATA	#IMPLIED
          flow-rate-usage-threshold     CDATA	#IMPLIED
          flow-rate-max-share          	CDATA	#IMPLIED
          dpd-timeout          	        CDATA	#IMPLIED
          natt-keepalive-interval       CDATA	#IMPLIED
          routing                      (host|optimized) #IMPLIED
          fragment-policy              (loose|strict|none|nofrags) #IMPLIED
          broadcast-icmp               (drop|allow) #IMPLIED>

<!-- Handling of ssh_pme_redo_flows() callback from the policymanager -->
<!--     and associated things. -->
<!ELEMENT engine-flows                  EMPTY>
<!ATTLIST engine-flows
          refresh                       CDATA   "0">

<!-- An address pool for NAT-T to make clients unique at server. -->
<!ELEMENT internal-nat	EMPTY>
<!ATTLIST internal-nat
          first-ip	CDATA	#REQUIRED
	  last-ip	CDATA	#REQUIRED>

<!-- Audit Configuration. -->
<!ELEMENT audit	(module*)>
<!ATTLIST audit
          snap-length	CDATA	      "0">

<!ELEMENT module	EMPTY>
<!ATTLIST module
	  log-to        CDATA	      "syslog"
	  format	NMTOKENS      "default">
<!-- all ike pm appgw engine -->
<!ATTLIST module
          subsystem     NMTOKENS      "all">

<!-- HTTP statistics interface. -->
<!ELEMENT http-interface	EMPTY>
<!ATTLIST http-interface
	  address		CDATA		#IMPLIED
	  port			CDATA		"7368"
	  frames		(yes|no)	"no"
	  refresh		CDATA		"0">

<!-- DNS name resolver utilization. -->
<!ELEMENT dns                   EMPTY>

<!-- XAUTH tester. -->
<!ELEMENT xauth-tester	ANY>

<!-- Mobike. rrc-policy: before-sa-update after-sa-update no-rrc -->
<!ELEMENT mobike                EMPTY>
<!ATTLIST mobike
          rrc-policy            CDATA           #IMPLIED>

<!-- Address pool for allocating IP addresses for remote access -->
<!-- clients. -->
<!ELEMENT address-pool	(subnet*,address+,ipv6-prefix?)>
<!ATTLIST address-pool
	  name    	ID	#IMPLIED
	  own-ip	CDATA	#IMPLIED
	  dns		CDATA	#IMPLIED
	  wins		CDATA	#IMPLIED
	  dhcp		CDATA	#IMPLIED>

<!-- Additional sub-networks, protected by the gateway -->
<!-- (SUBNET/MASKLEN). -->
<!ELEMENT subnet	(#PCDATA)>

<!-- IPv6 prefix, used when clients specify the low-order address bits -->
<!ELEMENT ipv6-prefix	(#PCDATA)>

<!-- An IP address specification.  Possible formats are: 		-->
<!--   IPADDR	 	a single IP address 				-->
<!--   IPADDR-IPADDR	an IP address range 				-->
<!--   IPADDR/MASKLEN	all addresses of the subnet.  If the netmask	-->
<!--   			attribute is unspecified, use the netmask	-->
<!--   			MASKLEN. 					-->
<!ELEMENT address	(#PCDATA)>
<!ATTLIST address
          netmask	CDATA	#IMPLIED>

<!-- Externalkey provider. -->
<!ELEMENT externalkey	EMPTY>
<!ATTLIST externalkey
	  type		CDATA		#REQUIRED
	  init-info	CDATA		#IMPLIED>

<!-- trust-cas -->
<!ATTLIST externalkey
	  flags		NMTOKENS	#IMPLIED>

<!-- An LDAP server. -->
<!ELEMENT ldap EMPTY>
<!ATTLIST ldap
	  server	CDATA	#REQUIRED
	  port		CDATA	"389">

<!-- Remote access client authentication. -->
<!ELEMENT client-auth	EMPTY>
<!ATTLIST client-auth
          type		(l2tp|xauth|eap)            #IMPLIED
	  gateway	CDATA		            #IMPLIED
          order         (1|2)                       #IMPLIED
	  user-name	CDATA		            #REQUIRED
	  password	CDATA		            #REQUIRED>

<!-- Authentication domains -->
<!ELEMENT auth-domain ((remote-secret
                       |certificate
		       |ca
                       |crl
                       |public-key
                       |private-key
                       |eap
                       |radius-client|radius
                       |password)*)>
<!ATTLIST auth-domain
          name          CDATA    #IMPLIED>

<!-- User-name - password based authentication at the remote access -->
<!-- gateway. -->
<!ELEMENT password	EMPTY>
<!ATTLIST password
	  user-name	CDATA	#REQUIRED
	  password	CDATA	#REQUIRED
	  user-name-encoding	(binary|hex)		"binary"
	  password-encoding	(binary|hex)		"binary">

<!-- Additional manually configured certificates and CRLs. -->

<!ELEMENT certificate	(#PCDATA)>
<!ATTLIST certificate
          file		CDATA	#IMPLIED>

<!ELEMENT crl		(#PCDATA)>
<!ATTLIST crl
          file		CDATA	#IMPLIED>

<!-- A pre-shared key for a remote IKE peer. -->
<!ELEMENT remote-secret		(#PCDATA)>
<!ATTLIST remote-secret
	  id-type	(dn|ip|fqdn|email|key-id|idlist)	#IMPLIED
	  id		CDATA			    		#IMPLIED
	  id-encoding	(binary|hex)		    		"binary"
	  encoding	(binary|hex)		    		"binary">

<!-- EAP configuration -->
<!ELEMENT eap           EMPTY>
<!ATTLIST eap
          type          (md5-challenge|sim|aka|srp|tls|aka-dash) #IMPLIED
          radius-url    CDATA                                   #IMPLIED
	  preference    CDATA                                   #IMPLIED>

<!-- NAT configuration. -->
<!ELEMENT nat 		EMPTY>
<!ATTLIST nat
	  type		(port|host)	"port"
	  ifname	CDATA		#REQUIRED
          src-port-preservation (loose|strict|overload|off) #IMPLIED>

<!-- ipv6  -->
<!ATTLIST nat
	  flags		NMTOKENS	#IMPLIED>


<!-- RADIUS client information. -->
<!ELEMENT radius-client		EMPTY>
<!ATTLIST radius-client
          address		CDATA	#IMPLIED
	  port			CDATA	#IMPLIED
	  nas-ip-address	CDATA	#IMPLIED
	  nas-identifier	CDATA	#IMPLIED
	  max-retransmit-timer	CDATA	#IMPLIED
	  max-retransmissions	CDATA	#IMPLIED>

<!-- RADIUS server information. -->
<!ELEMENT radius	EMPTY>
<!ATTLIST radius
	  server	CDATA	#REQUIRED
	  port		CDATA	"1812"
	  acct-port	CDATA	"1813"
	  secret	CDATA	#REQUIRED>

<!-- Access control group. -->
<!ELEMENT group	(constraint+)>
<!ATTLIST group
	  name	CDATA	#REQUIRED>

<!-- Constraint for members of an access control group. -->
<!ELEMENT constraint	EMPTY>
<!ATTLIST constraint
	  type		(xauth
	                 |eap
                         |key-subject
                         |eap-subject
	  		 |cert-subject
			 |cert-issuer
			 |ca-subject)			#REQUIRED>
<!-- Type			Field	Pattern 			-->
<!-- ================================================================== -->
<!-- xauth	  		radius 	AVP=PATTERN			-->
<!-- For `{cert,ca}-subject'	dn	PATTERN for subjectName		-->
<!-- and `cert-issuer'	  	ip	PATTERN for IP subjectAltName 	-->
<!-- types			fqdn	PATTERN for fqdn subjectAltName -->
<!--   				email	PATTERN for emailsubjectAltName -->
<!-- key-subject may use ip, fqdn, email and key-id types -->


<!-- eap   auth-method  PATTERN sim|aka|tls|md5-challenge|aka-dash      -->
<!-- eap-subject Field may be ip, fqdn, email or key-id                 --> 
<!-- eap-subject Pattern  should match the EAP identity                 -->

<!ATTLIST constraint
	  field		CDATA				#IMPLIED
	  pattern	CDATA				#IMPLIED>


<!-- Type of External authentication method used for authentication. -->
<!-- The method type and flag values should have the following values-->
<!--  Type                              FLAG                         -->
<!-- =============================================================== -->
<!-- generic                           simple                        -->
<!--                                   securid                       -->
<!-- radius-chap                                                     -->
<!-- otp                                                             -->
<!-- s-key                                                           -->
<!ELEMENT xauth-method EMPTY>
<!ATTLIST xauth-method
          type     CDATA #IMPLIED
          flag     CDATA #IMPLIED>


<!-- Standalone configuration for routes. Either ifname or ifnum for	-->
<!-- compatibility 							-->
<!ELEMENT route	EMPTY>
<!ATTLIST route
	  dst	 CDATA	#REQUIRED
	  gw 	 CDATA	#REQUIRED
	  ifnum	 CDATA	#IMPLIED
          ifname CDATA  #IMPLIED>

<!-- Standalone configuration for media address configuration. Either  -->
<!-- ifname or ifnum for compatibility.                                -->
<!ELEMENT media EMPTY>
<!ATTLIST media
	  ip	 CDATA	        #REQUIRED
	  mac	 CDATA		#REQUIRED
	  ifnum	 CDATA		#IMPLIED
          ifname CDATA		#IMPLIED
	  flags	 NMTOKENS	#IMPLIED>


<!-- IPSec over TCP encapsulation configuration -->
<!ELEMENT tcpencap       (local-ip?,peer?)>
<!ATTLIST tcpencap
          local-port     CDATA   "0"
          peer-port      CDATA   "0"
	  ike-port       CDATA   "0">


<!-- Policy element. -->
<!ELEMENT policy ((ldap|password|ike-defaults|certificate|crl|nat
                   |group)*
                  ,(service|tunnel|rule)+)>
<!ATTLIST policy
	  id		ID	#IMPLIED
	  precedence	CDATA	#IMPLIED
	  size		CDATA	#IMPLIED
	  refresh	CDATA	"0">

<!-- Default IKE parameters and algorithms. -->
<!ELEMENT ike-defaults	EMPTY>
<!-- cipher1 cipher2 null des 3des aes mac1 mac2 md5 sha1 -->
<!ATTLIST ike-defaults
	  algorithms	NMTOKENS	#IMPLIED>

<!-- A service object. -->
<!ELEMENT service	(appgw?)>
<!ATTLIST service
	  name		ID	#REQUIRED>

<!-- Application level gateway configuration. -->
<!ELEMENT appgw		ANY>
<!ATTLIST appgw
	  id		CDATA	#REQUIRED>

<!-- A tunnel specification. -->
<!ELEMENT tunnel	((ike-versions
			 |ike-groups
			 |pfs-groups
                         |life
                         |certificate
			 |identity
                         |authentication
			 |cfgmode-address
			 |virtual-ifname
			 |ike-algorithms
			 |ike-window-size
			 |local-ip
			 |local-interface
			 |local-port
			 |peer
			 |algorithm-properties
			 |manual-key
			 |inbound-extension
			 |tcpencap
			 |tunnel-address-pool
			 |outer-tunnel)*)>

<!ATTLIST tunnel
	  name		ID		#REQUIRED
	  app-id	CDATA		#IMPLIED
	  ike-life	CDATA		#IMPLIED>

<!-- cipher1 cipher2 null des 3des aes aes-ctr aes-gcm aes-gcm-64 -->
<!-- mac1 mac2 md5 sha1 sha2 xcbc-aes gmac-aes deflate lzs -->
<!-- esp ipcomp ah -->
<!-- Default transform is "esp aes 3des sha1 md5" for
     tunnel without dont-initiate flag and it is
     "esp aes aes-ctr aes-gcm 3des sha1 md5" for tunnel
     with dont-initiate flag -->

<!ATTLIST tunnel
	  transform	NMTOKENS	#IMPLIED>

<!-- perhost perport dont-initiate interface-trigger dhcp -->
<!-- omit-trigger-packet cfgmode l2tp aggressive-mode allow-dhcp -->
<!-- allow-cfgmode require-cfgmode auto allow-l2tp proxy-arp -->
<!-- tunnel transport internal-nat disable-anti-replay eap-request-id -->
<!-- port-nat start-with-natt dont-initiate-natt -->
<!-- disable-natt no-nats-allowed xauth-methods -->
<!-- enable-outbound-sa-selectors long-seq short-seq no-cert-chains -->
<!ATTLIST tunnel
	  flags		NMTOKENS	#IMPLIED>

<!-- An IKE peer, IP address or Domain name -->
<!ELEMENT peer	(#PCDATA)>

<!-- Local IP address to be used with a tunnel. -->
<!ELEMENT local-ip	(#PCDATA)>
<!ATTLIST local-ip
          precedence    NMTOKENS 	#IMPLIED>

<!-- Local interface to be used with a tunnel. -->
<!ELEMENT local-interface (#PCDATA)>
<!ATTLIST local-interface
          precedence    NMTOKENS 	#IMPLIED>

<!-- Local IKE port to be used with the tunnel. -->
<!ELEMENT local-port    (#PCDATA)>

<!-- Request this IP address when doing IKE CFGMODE. -->
<!ELEMENT cfgmode-address	(#PCDATA)>

<!-- Use this virtual adapter. -->
<!ELEMENT virtual-ifname	(#PCDATA)>

<!-- Allowed Diffie-Hellman groups for IKE. -->
<!ELEMENT ike-groups	(#PCDATA)>
<!-- system-preferences -->
<!ATTLIST ike-groups
	  flags		NMTOKENS	#IMPLIED>

<!-- Allowed IKE versions, currently support 1 and 2.   -->
<!-- If both given, initiator starts with version 2.    -->
<!-- If only 2 given start with version 2, no fallback. -->
<!-- If only 1 given, start with version 1, and on responder set USE_V1. -->
<!ELEMENT ike-versions (#PCDATA)>

<!-- Additional manually configured private key. -->
<!ELEMENT private-key	(#PCDATA)>
<!ATTLIST private-key
          file		CDATA	#IMPLIED>

<!-- Additional manually configured public key. -->
<!ELEMENT public-key	(#PCDATA)>
<!ATTLIST public-key
          file		CDATA	#IMPLIED>

<!-- Perfect forward secrecy. -->
<!ELEMENT pfs-groups	(#PCDATA)>
<!-- system-preferences -->
<!ATTLIST pfs-groups
	  flags		NMTOKENS	#IMPLIED>

<!-- A required access control group. -->
<!ELEMENT access-group	(#PCDATA)>

<!-- SA lifetime. -->
<!ELEMENT life	(#PCDATA)>
<!ATTLIST life
	  type	(kbytes|seconds)	%default-life-type;>

<!-- Trusted CA. -->
<!ELEMENT ca	(#PCDATA)>
<!ATTLIST ca
	  file  CDATA		#IMPLIED>
<!-- no-crl -->
<!ATTLIST ca
	  flags	NMTOKENS	#IMPLIED>

<!-- An IKE identity. -->
<!ELEMENT identity (local-secret*)>

<!-- A pre-shared key for tunnel authenticaton. -->
<!-- use-remote -->
<!ELEMENT local-secret		                  (#PCDATA)>
<!ATTLIST local-secret
	  encoding	(binary|hex)		   "binary"
          flags         NMTOKENS                   #IMPLIED>


<!ATTLIST identity
	  id-type	(dn|ip|fqdn|email|key-id|idlist)	#IMPLIED
	  id		CDATA			    		#IMPLIED
	  id-encoding	(binary|hex)		    		"binary"
	  type		(local|remote)          		"local"
          order         (1|2)                                   "1">

<!-- enforce-identity -->
<!ATTLIST identity
	  flags	NMTOKENS	#IMPLIED>

<!-- Tunnel authentication -->
<!ELEMENT authentication	EMPTY>
<!ATTLIST authentication
	  auth-domain-name      CDATA	        #IMPLIED
          order                 (1|2)           "1">

<!-- Algorithm properties. -->
<!ELEMENT algorithm-properties	EMPTY>
<!-- cipher1 cipher2 aes aes-ctr aes-gcm gmac-aes sha2 mac1 mac2 -->

<!ATTLIST algorithm-properties
	  algorithm		NMTOKENS	#REQUIRED>

<!ATTLIST algorithm-properties
	  min-key-size		CDATA		#REQUIRED
	  max-key-size		CDATA		#REQUIRED
	  default-key-size	CDATA		#REQUIRED
	  scope			(ike|ipsec|all)	"all">

<!-- Algorithms for IKE SAs. -->
<!-- cipher1 cipher2 des 3des aes mac1 mac2 md5 sha1 sha2 xcbc-aes -->
<!ELEMENT ike-algorithms	(#PCDATA)>

<!ELEMENT ike-window-size	(#PCDATA)>

<!-- Configuring extension selector under decapsulation -->
<!ELEMENT inbound-extension   EMPTY>
<!ATTLIST inbound-extension
	  index		CDATA	#REQUIRED
          dst           CDATA   #REQUIRED>

<!-- Configuring nested tunnels -->
<!ELEMENT outer-tunnel  EMPTY>
<!ATTLIST outer-tunnel
          name          CDATA                   #REQUIRED>

<!-- No flags specified at the moment. -->
<!ATTLIST outer-tunnel
          flags         NMTOKENS                #IMPLIED>

<!-- Configuring address pools to tunnels -->
<!ELEMENT tunnel-address-pool  EMPTY>
<!ATTLIST tunnel-address-pool
          name          IDREF                   #REQUIRED>

<!-- Manually configured SAs. -->

<!ELEMENT manual-key	(esp|ah|ipcomp)+>

<!ELEMENT esp		EMPTY>
<!ATTLIST esp
	  spi-in	CDATA	#REQUIRED
	  spi-out	CDATA	#REQUIRED
	  encr-key-in	CDATA	#IMPLIED
	  encr-key-out	CDATA	#IMPLIED
	  auth-key-in	CDATA	#IMPLIED
	  auth-key-out	CDATA	#IMPLIED>

<!ELEMENT ah		EMPTY>
<!ATTLIST ah
	  spi-in	CDATA	#REQUIRED
	  spi-out	CDATA	#REQUIRED
	  auth-key-in	CDATA	#REQUIRED
	  auth-key-out	CDATA	#REQUIRED>

<!ELEMENT ipcomp		EMPTY>
<!ATTLIST ipcomp
	  cpi-in	CDATA	#REQUIRED
	  cpi-out	CDATA	#REQUIRED>

<!-- A policy rule. -->
<!ELEMENT rule ((src|src-dns)?,(dst|dst-dns)?,
		(ifname?|routed-ifname?),
		local-stack?,
		access-group*,
		extension*)>

<!ATTLIST rule
	  app-id	ID		        #IMPLIED
	  precedence	CDATA			#IMPLIED
	  type		(pass|reject|drop)	%default-rule-type;
	  from-tunnel	IDREF			#IMPLIED
	  to-tunnel	IDREF			#IMPLIED
          nat-dst       CDATA                   #IMPLIED
          nat-dst-low   CDATA                   #IMPLIED
          nat-dst-high  CDATA                   #IMPLIED
          nat-dst-port  CDATA                   #IMPLIED
          nat-src       CDATA                   #IMPLIED
          nat-src-low   CDATA                   #IMPLIED
          nat-src-high  CDATA                   #IMPLIED
          nat-src-port  CDATA                   #IMPLIED
          nat-src-port-preservation (loose|strict|overload|off) #IMPLIED
          nat-src-type  (one-to-one)            #IMPLIED
          nat-dst-type  (one-to-one)            #IMPLIED
	  service	IDREF			#IMPLIED>

<!-- connections -->
<!ATTLIST rule
	  log		NMTOKENS		#IMPLIED>

<!-- no-flow rate-limit multi-homed set-df clear-df  -->
<!-- match-local-ike adjust-local-address            -->
<!ATTLIST rule
	  flags		NMTOKENS		#IMPLIED>

<!-- Rule selectors. -->

<!ELEMENT src		(#PCDATA)>
<!ELEMENT dst		(#PCDATA)>
<!ELEMENT src-dns	(#PCDATA)>
<!ELEMENT dst-dns	(#PCDATA)>
<!ELEMENT ifname	(#PCDATA)>
<!ELEMENT routed-ifname	(#PCDATA)>

<!ELEMENT local-stack	EMPTY>
<!ATTLIST local-stack
	  direction	(from|to)	#REQUIRED>

<!ELEMENT extension	EMPTY>
<!ATTLIST extension
	  id		CDATA	#REQUIRED
	  low		CDATA	#REQUIRED
	  high		CDATA	#REQUIRED>

=== invisiblek/kernel_808l/drivers/net/eip93_drivers/quickSec/src/ipsec/quicksec/samples/appgw_ftp.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">
<!--
The format of the FTP ALG config data is:

  <!ELEMENT alg-ftp             (disable|content-filter)*>

    client-can-change-ip server-can-change-ip
  <!ATTLIST alg-ftp
            flags               NMTOKENS        #IMPLIED>

  <!ELEMENT disable             (#PCDATA)>
  <!ELEMENT content-filter      (#PCDATA)>

 -->
<quicksec>
  <policy>
    <!-- FTP application gateway. -->
    <service name="ftp">
      <appgw id="alg-ftp@ssh.com">
        <!-- Configuration data for FTP appgw. -->
        <alg-ftp>
          <disable>UPLOAD</disable>
          <content-filter>MD5</content-filter>
        </alg-ftp>
      </appgw>
    </service>

    <!-- Application gateway for FTP traffic. -->
    <rule service="ftp" log="connections">
      <src>ipv4(tcp,0.0.0.0/0)</src>
      <dst>ipv4(tcp:21,0.0.0.0/0)</dst>
    </rule>
    <rule service="ftp" log="connections">
      <src>ipv6(tcp,::/0)</src>
      <dst>ipv6(tcp:21,::/0)</dst>
    </rule>

    <!-- Pass everything else in plain-text from the private interface. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
      <local-stack direction="from"/>
    </rule>
  </policy>
</quicksec>

=== invisiblek/kernel_808l/drivers/net/eip93_drivers/quickSec/src/ipsec/quicksec/samples_ori/hosta-access-group-psk.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Peer-to-peer setup with access groups using PSK. -->
<!-- Related: hostb-access-group-psk.xml -->
<quicksec>
  <params>
    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- shared secret and identity of remote IKE peer -->
      <remote-secret id-type="email" 
                     id="user1@safenet-inc.com">foo</remote-secret>
      
      <remote-secret id-type="email" 
                     id="user2@safenet-inc.com">foobar</remote-secret>
    </auth-domain>
    
    <!-- Access groups that limit access based on the identity
         sent by remote IKE peer. The pattern can be a regular
         expression for example pattern="*@safenet-inc.com". -->
    <group name="trusted-user1">
      <constraint type="key-subject" field="email"
                  pattern="user1@safenet-inc.com"/>
    </group>

    <group name="trusted-user2">
      <constraint type="key-subject" field="email"
                  pattern="user2@safenet-inc.com"/>
    </group>
  </params>
  <policy>

    <tunnel name="host-to-host">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="a@safenet-inc.com">
        <!-- local shared secret -->
        <local-secret>foo</local-secret>
      </identity>
    </tunnel>

    <!-- Allows src address to initiate traffic to the dst address, 
         if the packet came from the specified from-tunnel.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule from-tunnel="host-to-host">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(172.30.4.189)</dst>
      <!-- Allow access to users that provide the identity defined
           in the group elements listed below. -->
      <access-group>trusted-user1</access-group>
      <access-group>trusted-user2</access-group>
    </rule>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>

  </policy>
</quicksec>

=== invisiblek/kernel_808l/drivers/net/eip93_drivers/quickSec/src/ipsec/quicksec/samples_ori/hosta-sctp.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">
<quicksec>
  <params>
    <http-interface/>

    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <remote-secret id-type="email" 
                     id="b@safenet-inc.com">foo</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <tunnel name="sctp-host" ike-life="3600" flags="transport">
      <identity id-type="email" id="a@safenet-inc.com"> 
        <local-secret>foo</local-secret>
      </identity>
      <ike-versions>2 1</ike-versions>
    </tunnel>

    <rule to-tunnel="sctp-host" flags="multi-homed"> 
      <src>ipv4(sctp,172.30.4.189),ipv4(sctp,10.0.0.2)</src>
      <dst>ipv4(sctp,172.30.4.167),ipv4(sctp,10.0.0.1)</dst>
    </rule>

    <rule from-tunnel="sctp-host" flags="multi-homed">
      <src>ipv4(sctp,172.30.4.167),ipv4(sctp,10.0.0.1)</src>
      <dst>ipv4(sctp,172.30.4.189),ipv4(sctp,10.0.0.2)</dst>
    </rule>

    <!-- Pass everything else in plain-text. -->
    <rule/>
  </policy>
</quicksec>

=== invisiblek/kernel_808l/drivers/net/eip93_drivers/quickSec/src/ipsec/quicksec/samples/hostb-nested.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Nested tunnel setup, tunnel hosta-hostc is sent through a 
     tunnel hosta-hostb. 
     hosta = hostb - hostc -->
<!-- Related: hosta-nested.xml, hostc-nested.xml -->
<quicksec>
  <params>
    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- shared secret and identity of remote IKE peers -->
      <remote-secret id-type="email" 
                     id="a@safenet-inc.com">foo</remote-secret>
    </auth-domain>

    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain name="auth2">
      <remote-secret id-type="email" 
                     id="c@safenet-inc.com">car</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <!-- Outer ESP tunnelmode tunnel -->
    <tunnel name="outer" transform="esp aes sha1">
      <identity id-type="email" id="b@safenet-inc.com">
        <local-secret>foo</local-secret>
      </identity>
      <local-ip>172.30.4.167</local-ip>
      <peer>172.30.4.189</peer>      
    </tunnel>

    <!-- Inner ESP transportmode tunnel -->
    <tunnel name="inner" transform="esp aes sha1" flags="transport">
      <identity id-type="email" id="b@safenet-inc.com">
        <local-secret>foo</local-secret>
      </identity>
      <!-- Authentication domain used in IKE authentication -->
      <authentication auth-domain-name="auth2"/>
      <!-- Specify name of outer tunnel to use for this tunnel. -->
      <outer-tunnel name="outer"/>
    </tunnel>

    <!-- Allows plaintext packets to be tunneled to hostc using end-to-end 
         transportmode ESP nested inside tunnelmode ESP between hosta 
         and hostb. -->
    <rule to-tunnel="inner">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(tcp,192.168.1.2),ipv4(udp,192.168.1.2),ipv4(icmp,192.168.1.2)
      </dst>
    </rule>

    <rule from-tunnel="inner">
      <src>ipv4(tcp,192.168.1.2),ipv4(udp,192.168.1.2),ipv4(icmp,192.168.1.2)
      </src>
      <dst>ipv4(172.30.4.167)</dst>
    </rule>

    <!-- Allows plaintext packets to be tunneled to netb using 
         tunnelmode ESP. Matches also ESP + IKE packets encapsulated using 
         the inner tunnel. Flag `match-local-ike' speci fies that the rule
         overrides system default IKE passby rules. --> 
    <rule to-tunnel="outer" flags="match-local-ike">
      <dst>ipv4(192.168.1.0/24)</dst>
    </rule>

    <rule from-tunnel="outer">
      <src>ipv4(192.168.1.0/24)</src>
    </rule>

    <!-- Default passby rule. -->
    <rule/>

  </policy>
</quicksec>

=== invisiblek/kernel_808l/drivers/net/eip93_drivers/quickSec/src/ipsec/quicksec/samples_ori/hostb-ikev1-cfgmode-client.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Remote access setup with IKEv1. -->
<!-- Related: hosta-ikev1-cfgmode-gw.xml -->
<quicksec>
  <params>
    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- Shared secret and the identity of the remote IKE peer. -->
      <remote-secret id-type="email" 
                     id="a@safenet-inc.com">foo</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <!-- The cfgmode flag enables the configuration payload
         client side support. The auto flag establishes the
         IKEv1 and IPsec SAs automatically when 
         Policy Manager is started. -->
    <tunnel name="host-to-host" flags="cfgmode auto aggressive-mode">
      <!-- Local identity sent to the remote IKE peer. -->
      <identity id-type="email" id="b@safenet-inc.com">
        <!-- Local shared secret. -->
        <local-secret>foo</local-secret>
      </identity>
      <!-- The IP address of the CFGMODE sever, from where we
           get the virtual IP. -->
      <peer>172.30.4.189</peer>
      <ike-versions>1</ike-versions>
    </tunnel>

    <!-- As we do not know which virtual IP address the IRAS is going
         to assign to us, we don't need the src element. The flag
         `adjust-local-address' will cause the local traffic selector
         to be set to the virtual IP address when using IKEv1. With
         IKEv2 this is negotiated with the gateway and done
         automatically. We fill the dst element with the known
         VPN subnets. -->
    <rule to-tunnel="host-to-host" flags="adjust-local-address">
      <local-stack direction="from"/>
    </rule>

    <!-- A pass rule that handles all the traffic not matching
         the traffic selectors of any higher precedence rules.
         Remove this rule if plaintext traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>
